name: jjgan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.2.0=py38hca03da5_0
  - aom=3.5.0=h7ea286d_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py38hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h1a28f6b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38hca03da5_0
  - attrs=23.1.0=py38hca03da5_0
  - babel=2.11.0=py38hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py38hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py38hc377ac9_7
  - bzip2=1.0.8=h80987f9_5
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2023.12.12=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2024.2.2=py38hca03da5_0
  - cffi=1.16.0=py38h80987f9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38hca03da5_0
  - comm=0.2.1=py38hca03da5_0
  - contourpy=1.0.5=py38h525c30c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.6.7=py38h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dlib=19.24.0=py38hc3f2b88_3
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py38hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h313beb8_0
  - ffmpeg=5.1.2=gpl_hf318d42_106
  - filelock=3.13.1=py38hca03da5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hee714a5_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - fsspec=2023.10.0=py38hca03da5_0
  - gdown=5.1.0=pyhd8ed1ab_0
  - gettext=0.21.0=h13f89a0_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py38hca03da5_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py38h8c48613_0
  - gnutls=3.7.8=h9f1a10d_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.22.3=h514c7bf_0
  - gstreamer=1.22.3=h80987f9_0
  - harfbuzz=6.0.0=hddbc195_0
  - hdf5=1.14.0=nompi_h6b85c65_103
  - icu=70.1=h6b3803e_0
  - idna=3.4=py38hca03da5_0
  - importlib-metadata=7.0.1=py38hca03da5_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.1=py38hca03da5_1
  - ipykernel=6.28.0=py38hca03da5_0
  - ipython=8.12.2=py38hca03da5_0
  - ipywidgets=8.1.2=py38hca03da5_0
  - jasper=2.0.33=hc3cd1e9_1
  - jbig=2.1=h1a28f6b_0
  - jedi=0.18.1=py38hca03da5_1
  - jinja2=3.1.3=py38hca03da5_0
  - joblib=1.2.0=py38hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py38hca03da5_0
  - jsonschema-specifications=2023.7.1=py38hca03da5_0
  - jupyter=1.0.0=py38hca03da5_9
  - jupyter-lsp=2.2.0=py38hca03da5_0
  - jupyter_client=8.6.0=py38hca03da5_0
  - jupyter_console=6.6.3=py38hca03da5_0
  - jupyter_core=5.5.0=py38hca03da5_0
  - jupyter_events=0.8.0=py38hca03da5_0
  - jupyter_server=2.10.0=py38hca03da5_0
  - jupyter_server_terminals=0.4.4=py38hca03da5_1
  - jupyterlab=4.0.11=py38hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py38hca03da5_0
  - jupyterlab_widgets=3.0.10=py38hca03da5_0
  - kiwisolver=1.4.4=py38h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.6=hb7217d7_1
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcblas=3.9.0=1_h9886b1c_netlib
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.5.0=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.8=h1a28f6b_5
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.17=h0d3ecfb_2
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - liblapack=3.9.0=1_h9886b1c_netlib
  - liblapacke=3.9.0=1_h9886b1c_netlib
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.21=h269037a_0
  - libopencv=4.7.0=py38h427f6f2_1
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h80987f9_0
  - libpq=15.2=h1a28acd_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.45.2=h091b4b1_0
  - libssh2=1.10.0=h02f6b3c_2
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.0=h313beb8_1
  - libunistring=0.9.10=h1a28f6b_0
  - libuv=1.44.2=h80987f9_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.11.0=hc377ac9_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.3=h67585b2_4
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.3=py38h80987f9_0
  - matplotlib=3.7.2=py38hca03da5_0
  - matplotlib-base=3.7.2=py38h46d7db6_0
  - matplotlib-inline=0.1.6=py38hca03da5_0
  - mistune=2.0.4=py38hca03da5_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py38hca03da5_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=ha71a6ea_2
  - mysql-common=8.0.32=h518ea0a_0
  - mysql-libs=8.0.32=hcb599eb_0
  - nbclient=0.8.0=py38hca03da5_0
  - nbconvert=7.10.0=py38hca03da5_0
  - nbformat=5.9.2=py38hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py38hca03da5_0
  - nettle=3.8.1=h63371fa_1
  - networkx=3.1=py38hca03da5_0
  - ninja=1.10.2=hca03da5_5
  - ninja-base=1.10.2=h525c30c_5
  - notebook=7.0.8=py38hca03da5_0
  - notebook-shim=0.2.3=py38hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numpy=1.24.3=py38h1398885_0
  - numpy-base=1.24.3=py38h90707a3_0
  - olefile=0.46=pyhd3eb1b0_0
  - opencv=4.7.0=py38h150bfb4_1
  - openh264=2.3.1=hb7217d7_2
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.13=h1a28f6b_0
  - overrides=7.4.0=py38hca03da5_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=23.1=py38hca03da5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - path=16.2.0=pyhd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre2=10.42=hb066dcc_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.2.0=py38h80987f9_0
  - pip=23.3.1=py38hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - pkgutil-resolve-name=1.3.10=py38hca03da5_1
  - platformdirs=3.10.0=py38hca03da5_0
  - ply=3.11=py38hca03da5_0
  - pooch=1.7.0=py38hca03da5_0
  - prometheus_client=0.14.1=py38hca03da5_0
  - prompt-toolkit=3.0.43=py38hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.21.12=py38h2b1e499_0
  - psutil=5.9.0=py38h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.7.0=py38hfbcc8b7_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38hca03da5_1
  - pyparsing=3.0.9=py38hca03da5_0
  - pyqt=5.15.10=py38h313beb8_0
  - pyqt5-sip=12.13.0=py38h80987f9_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.16=h3ba56d0_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38hca03da5_0
  - python-json-logger=2.0.7=py38hca03da5_0
  - python_abi=3.8=4_cp38
  - pytorch=2.2.1=py3.8_0
  - pytz=2023.3.post1=py38hca03da5_0
  - pyyaml=6.0.1=py38h80987f9_0
  - pyzmq=25.1.2=py38h313beb8_0
  - qt-main=5.15.8=hfe8d25c_6
  - qtconsole=5.5.1=py38hca03da5_0
  - qtpy=2.4.1=py38hca03da5_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py38hca03da5_0
  - requests=2.31.0=py38hca03da5_1
  - rfc3339-validator=0.1.4=py38hca03da5_0
  - rfc3986-validator=0.1.1=py38hca03da5_0
  - rpds-py=0.10.6=py38hf0e4da2_0
  - scikit-learn=0.24.0=py38h397cc00_0
  - scipy=1.10.1=py38h9d039d2_1
  - send2trash=1.8.2=py38hca03da5_0
  - sentry-sdk=1.9.0=py38hca03da5_0
  - setproctitle=1.2.2=py38h1a28f6b_0
  - setuptools=68.2.2=py38hca03da5_0
  - sip=6.7.12=py38h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - smmap=4.0.0=pyhd3eb1b0_0
  - sniffio=1.3.0=py38hca03da5_0
  - soupsieve=2.5=py38hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.4.1=h7ea286d_0
  - sympy=1.12=py38hca03da5_0
  - terminado=0.17.1=py38hca03da5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py38hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=py38hca03da5_0
  - torchvision=0.17.1=py38_cpu
  - tornado=6.3.3=py38h80987f9_0
  - tqdm=4.65.0=py38h86d0a89_0
  - traitlets=5.7.1=py38hca03da5_0
  - typing-extensions=4.9.0=py38hca03da5_1
  - typing_extensions=4.9.0=py38hca03da5_1
  - urllib3=2.1.0=py38hca03da5_1
  - wandb=0.16.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38hca03da5_1
  - websocket-client=0.58.0=py38hca03da5_4
  - wheel=0.41.2=py38hca03da5_0
  - widgetsnbextension=4.0.10=py38hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.17.0=py38hca03da5_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=hd90d995_0
prefix: /Users/ericli/anaconda3/envs/jjgan
